# Generated by Django 4.2.30 on 2026-07-29 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('icon', models.CharField(blank=True, default='', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CategoryField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=150)),
                ('key', models.SlugField(help_text='Machine-readable key used in API payloads (auto-generated from label).', max_length=100)),
                ('placeholder', models.CharField(blank=True, default='', max_length=200)),
                ('help_text', models.CharField(blank=True, default='', max_length=300)),
                ('required', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('default_value', models.CharField(blank=True, default='', max_length=255)),
                ('min_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('min_length', models.PositiveIntegerField(blank=True, null=True)),
                ('max_length', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_fields', to='categories.category')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FieldDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Textarea'), ('number', 'Number'), ('select', 'Select'), ('radio', 'Radio'), ('checkbox', 'Checkbox / Multiselect'), ('boolean', 'Boolean (Yes/No)'), ('date', 'Date')], max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FieldOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=150)),
                ('value', models.CharField(max_length=150)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('category_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='categories.categoryfield')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FieldCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(choices=[('equals', 'Equals'), ('not_equals', 'Does not equal'), ('contains', 'Contains'), ('not_contains', 'Does not contain'), ('greater_than', 'Greater than'), ('less_than', 'Less than')], max_length=20)),
                ('value', models.CharField(help_text='The value to compare against (e.g. "true", "256").', max_length=255)),
                ('category_field', models.ForeignKey(help_text='The field whose visibility is controlled.', on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='categories.categoryfield')),
                ('depends_on', models.ForeignKey(help_text='The field whose value is evaluated.', on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='categories.categoryfield')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='categoryfield',
            name='field_definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_fields', to='categories.fielddefinition'),
        ),
        migrations.AlterUniqueTogether(
            name='categoryfield',
            unique_together={('category', 'key')},
        ),
    ]
